[project]
name = "calorai-pipecat-whatsapp-calling"
version = "0.1.0"
description = "A real-time voice bot that integrates with WhatsApp Business API"
readme = "README.md"
requires-python = ">=3.10,<3.13"    # restrict to known-working range
dependencies = [
    "pipecat-ai[openai,deepgram,silero,webrtc,runner]>=0.0.105",
    "pipecatcloud>=0.0.1",
    "numba==0.61.2",
    "llvmlite==0.44.0",
    "python-dotenv>=1.2.2",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "ruff~=0.12.1",
    "uvicorn>=0.32.0,<1.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "fastapi>=0.115.6,<0.117.0"
]